#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 15 15:40:58 2022

@author: nn819853
"""

import sys
sys.path.append('/home/users/nn819853/Documents/python_code')

import iris
import numpy as np
import matplotlib.pyplot as plt
import iris.quickplot as qplt
import iris.plot as iplt
import Documents.python_code.diagnostics.file_locations_module as file_loc
import diagnostics.radiative_fluxes.fluxes_module as flux_mod
import soc_fluxes_module as soc_flux


diag_dir = file_loc.diag_dir + 'socrates_diags/'

cd964_ukesm_file = diag_dir + 'cd964a.p620140529_all_clear_clearclean_fluxes.pp'


# Load ukesm fluxes
cd964_ukesm_sw_up, cd964_ukesm_sw_down,\
cd964_ukesm_lw_up, cd964_ukesm_lw_down,\
cd964_ukesm_clear_sw_up, cd964_ukesm_clear_sw_down,\
cd964_ukesm_clear_lw_up, cd964_ukesm_clear_lw_down,\
cd964_ukesm_clearclean_sw_up, cd964_ukesm_clearclean_sw_down,\
cd964_ukesm_clearclean_lw_up, cd964_ukesm_clearclean_lw_down=\
soc_flux.load_ukesm_data(cd964_ukesm_file)

# Calculate UKESM net down fluxes
cd964_ukesm_net_down_sw, cd964_ukesm_net_down_lw, cd964_ukesm_net_down_total =\
soc_flux.ukesm_net_down_fluxes(cd964_ukesm_sw_up, cd964_ukesm_sw_down, cd964_ukesm_lw_up)
cd964_ukesm_clear_net_down_sw, cd964_ukesm_clear_net_down_lw, cd964_ukesm_clear_net_down_total =\
soc_flux.ukesm_net_down_fluxes(cd964_ukesm_clear_sw_up, cd964_ukesm_clear_sw_down, cd964_ukesm_clear_lw_up)
cd964_ukesm_clearclean_net_down_sw, cd964_ukesm_clearclean_net_down_lw, cd964_ukesm_clearclean_net_down_total =\
soc_flux.ukesm_net_down_fluxes(cd964_ukesm_clearclean_sw_up, cd964_ukesm_clearclean_sw_down, cd964_ukesm_clearclean_lw_up)


# Load socrates flux cubes
sky_types = ['',\
             'clear_sky_', 'clearclean_sky_'\
                 ]

cd964_soc_cubes = soc_flux.load_soc_flux_multi(sky_types, diag_dir, 'cd964',\
                                        '20140529', 'toa',\
                                        'no_ice_cloud.nflx',\
                                        cd964_ukesm_sw_up)
    
# Extract cubes from the lists
cd964_soc_net_down_sw_toa, cd964_soc_net_down_lw_toa,\
cd964_soc_clear_net_down_sw_toa, cd964_soc_clear_net_down_lw_toa,\
cd964_soc_clearclean_net_down_sw_toa, cd964_soc_clearclean_net_down_lw_toa =\
cd964_soc_cubes

# Calculate SOCRATES total (sw + lw) net down fluxes
cd964_soc_net_down_total_toa = cd964_soc_net_down_sw_toa + cd964_soc_net_down_lw_toa
cd964_soc_clear_net_down_total_toa = cd964_soc_clear_net_down_sw_toa + cd964_soc_clear_net_down_lw_toa
cd964_soc_clearclean_net_down_total_toa = cd964_soc_clearclean_net_down_sw_toa + \
    cd964_soc_clearclean_net_down_lw_toa
    

# Calculate differences
total_diff = cd964_soc_net_down_total_toa - cd964_ukesm_net_down_total[85]
sw_diff = cd964_soc_net_down_sw_toa - cd964_ukesm_net_down_sw[85]
lw_diff = cd964_soc_net_down_lw_toa - cd964_ukesm_net_down_lw[85]
total_diff_clear = cd964_soc_clear_net_down_total_toa - cd964_ukesm_clear_net_down_total[85]
sw_diff_clear = cd964_soc_clear_net_down_sw_toa - cd964_ukesm_clear_net_down_sw[85]
lw_diff_clear = cd964_soc_clear_net_down_lw_toa - cd964_ukesm_clear_net_down_lw[85]
total_diff_clearclean = cd964_soc_clearclean_net_down_total_toa - cd964_ukesm_clearclean_net_down_total[85]
sw_diff_clearclean = cd964_soc_clearclean_net_down_sw_toa - cd964_ukesm_clearclean_net_down_sw[85]
lw_diff_clearclean = cd964_soc_clearclean_net_down_lw_toa - cd964_ukesm_clearclean_net_down_lw[85]


# PLotting
plot_dir = file_loc.plot_dir  + 'socrates_plots/'

soc_flux.plot_flux(cd964_soc_net_down_total_toa,
                   'SOC control TOA net down total flux 20140529 all sky no ice cloud',
                   plot_dir + 'soc_cont_toa_net_down_total_flux_20140529_all_sky_no_ice_cloud',
                   vmin=0, vmax=0,
                   )

soc_flux.plot_flux(cd964_soc_net_down_sw_toa,
                   'SOC control TOA net down sw flux 20140529 all sky no ice cloud',
                   plot_dir + 'soc_cont_toa_net_down_sw_flux_20140529_all_sky_no_ice_cloud',
                   vmin=0, vmax=0,
                   )

soc_flux.plot_flux(cd964_soc_net_down_lw_toa,
                   'SOC control TOA net down lw flux 20140529 all sky no ice cloud',
                   plot_dir + 'soc_cont_toa_net_down_lw_flux_20140529_all_sky_no_ice_cloud',
                   vmin=0, vmax=0,
                   )

soc_flux.plot_flux_diff(total_diff,\
                        'SOC - UKESM control net down total flux 20140529 all sky emis sea fix',\
                        plot_dir + 'flux_diff_soc-ukesm_control_net_down_total_flux_20140529_all_sky_emis_sea_fix',
                        vmin =-80, vmax =80 ,
                        )
soc_flux.plot_flux_diff(sw_diff,\
                        'SOC - UKESM control net down sw flux 20140529 all sky emis sea fix',\
                        plot_dir + 'flux_diff_soc-ukesm_control_net_down_sw_flux_20140529_all_sky_emis_sea_fix',
                        vmin =-80, vmax =80 ,
                        )
soc_flux.plot_flux_diff(lw_diff,\
                        'SOC - UKESM control net down lw flux 20140529 all sky emis sea fix',\
                        plot_dir + 'flux_diff_soc-ukesm_control_net_down_lw_flux_20140529_all_sky_emis_sea_fix',
                        vmin =-50, vmax =50 ,
                        )
# soc_flux.plot_flux_diff(total_diff_clear,\
#                         'SOC - UKESM control net down total flux 20140529 clear sky emis sea fix',\
#                         plot_dir + 'flux_diff_soc-ukesm_control_net_down_total_flux_20140529_clear_sky_emis_sea_fix',
#                         vmin =-10, vmax =10 ,
#                         )
# soc_flux.plot_flux_diff(sw_diff_clear,\
#                         'SOC - UKESM control net down sw flux 20140529 clear sky emis sea fix',\
#                         plot_dir + 'flux_diff_soc-ukesm_control_net_down_sw_flux_20140529_clear_sky_emis_sea_fix',
#                         vmin =-10, vmax =10 ,
#                         )
# soc_flux.plot_flux_diff(lw_diff_clear,\
#                         'SOC - UKESM control net down lw flux 20140529 clear sky emis sea fix',\
#                         plot_dir + 'flux_diff_soc-ukesm_control_net_down_lw_flux_20140529_clear_sky_emis_sea_fix',
#                         vmin =-10, vmax =10 ,
#                         )
# soc_flux.plot_flux_diff(total_diff_clearclean,\
#                         'SOC - UKESM control net down total flux 20140529 clearclean sky emis sea fix',\
#                         plot_dir + 'flux_diff_soc-ukesm_control_net_down_total_flux_20140529_clearclean_sky_emis_sea_fix',
#                         vmin =-3, vmax = 3,
#                         )
# soc_flux.plot_flux_diff(sw_diff_clearclean,\
#                         'SOC - UKESM control net down sw flux 20140529 clearclean sky emis sea fix',\
#                         plot_dir + 'flux_diff_soc-ukesm_control_net_down_sw_flux_20140529_clearclean_sky_emis_sea_fix',
#                         vmin =-1, vmax =1 ,
#                         )
# soc_flux.plot_flux_diff(lw_diff_clearclean,\
#                         'SOC - UKESM control net down lw flux 20140529 clearclean sky emis sea fix',\
#                         plot_dir + 'flux_diff_soc-ukesm_control_net_down_lw_flux_20140529_clearclean_sky_emis_sea_fix',
#                         vmin =-3, vmax =3 ,
#                         )

print('sw nans: ', np.where(np.isnan(cd964_soc_sw_net_down_toa.data)))
print('lw nans: ', np.where(np.isnan(cd964_soc_lw_net_down_toa.data)))